### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)'

### ISSUE THREAD

**Issue by SakurajimaMaii** [AAChartModel/AAChartCore-Kotlin#122]
java.lang.NoSuchMethodError: 'void com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)'
	at com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.safeEvaluateJavaScriptString(AAChartView.kt:327)
	at com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.setContentWidth(AAChartView.kt:71)
	at com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.setupBasicContent(AAChartView.kt:124)
	at com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.<init>(AAChartView.kt:111)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:325)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:174)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:135)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:294)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1127)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1130)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1101)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:505)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:360)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:443)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:121)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:717)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$9(RenderTask.java:873)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by juice31585** [comment]
I have the same problem with compose compilation

**Comment by newarifrh** [comment]
anyone have a solution?

**Comment by ShuaiXiu** [comment]
把代码拉下来，然后在报错的方法里加上if (isInEditMode) return 就可以预览了

**Comment by SakurajimaMaii** [comment]
该问题在 [PR 145](https://github.com/AAChartModel/AAChartCore-Kotlin/pull/145) 中被修复
