### ISSUE TITLE
开启混淆crash

### ISSUE THREAD

**Issue by 330676687** [AAChartModel/AAChartCore-Kotlin#72]
```
Thread Name: 'main'
Back traces starts.
java.lang.AssertionError: java.lang.NoSuchFieldException: Solid
	at e.i.d.a0.p.n$k0.<init>(TypeAdapters.java:12)
	at e.i.d.a0.p.n$w.a(TypeAdapters.java:5)
	at e.i.d.f.p(Gson.java:9)
	at e.i.d.a0.p.i.b(ReflectiveTypeAdapterFactory.java:4)
	at e.i.d.a0.p.i.e(ReflectiveTypeAdapterFactory.java:15)
	at e.i.d.a0.p.i.a(ReflectiveTypeAdapterFactory.java:4)
	at e.i.d.f.p(Gson.java:9)
	at e.i.d.a0.p.i.b(ReflectiveTypeAdapterFactory.java:4)
	at e.i.d.a0.p.i.e(ReflectiveTypeAdapterFactory.java:15)
	at e.i.d.a0.p.i.a(ReflectiveTypeAdapterFactory.java:4)
	at e.i.d.f.p(Gson.java:9)
	at e.i.d.a0.p.i.b(ReflectiveTypeAdapterFactory.java:4)
	at e.i.d.a0.p.i.e(ReflectiveTypeAdapterFactory.java:15)
	at e.i.d.a0.p.i.a(ReflectiveTypeAdapterFactory.java:4)
	at e.i.d.f.p(Gson.java:9)
	at e.i.d.f.E(Gson.java:1)
	at e.i.d.f.F(Gson.java:2)
	at e.i.d.f.A(Gson.java:2)
	at e.i.d.f.z(Gson.java:2)
	at com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.t(AAChartView.kt:3)
	at com.github.aachartmodel.aainfographics.aachartcreator.AAChartView.s(AAChartView.kt:1)
	at com.github.aachartmodel.aainfographics.aachartcreator.AAChartView$b.onPageFinished(AAChartView.kt:1)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:524)
	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:188)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
Caused by: java.lang.NoSuchFieldException: Solid
	at java.lang.Class.getField(Class.java:891)
	at e.i.d.a0.p.n$k0.<init>(TypeAdapters.java:6)
	... 29 more
Back traces ends.
```

**Comment by AAChartModel** [comment]
参考 #10 

> 非常感谢，我在混淆时排除了AAChartConfiger和AAOptionsModel两个包下的文件就ok了。
